version: '1'

services:
  mysql:
    image: mysql
    container_name: somt_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: somt
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      TZ: Asia/Seoul
      command: >
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"

  redis:
    image: redis
    container_name: somt_redis
    restart: always
    ports:
      - "6379:6379"
