spring :
  config :
    import : "application-secret.yml"

  application :
    name : smot

  jpa:
    hibernate:
      ddl-auto : none
      default_batch_fetch_size : 100
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false

  web:
    resources:
      cache:
        period: 3600


