spring :
  config :
    import : "application-secret.yml"

  application :
    name : smot

  jpa:
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true




