spring :
  datasource:
    url: jdbc:mysql://localhost:3306/somt
    username: user
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  redis:
    host: localhost
    port: 6379

  security:
    certified:
      no:
        - /api/auth/login
        - /h2-console
        - /api/auth/register
        - /api/login
        - /actuator/health
        - /
    time:
      access: 3600000
      refresh: 86400000


