spring :
  config :
    import : "application-secret.yml"

  application :
    name : smot

  jpa:
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  web:
    resources:
      cache:
        period: 3600


