openapi: 3.0.0
info:
  title: Order API
  version: 1.0.0
paths:
  /api/user/orders:
    post:
      summary: 주문 생성
      security:
        - bearerAuth: []
      responses:
        "201":
          description: 생성됨
        "400":
          description: "BAD_REQUEST"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: "ACCESS_DENIED"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      summary: 내 주문 목록 조회
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 30
      responses:
        "200":
          description: 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponsePage"
        "401":
          description: "ACCESS_DENIED"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/admin/orders:
    get:
      summary: 모든 주문 목록 조회 (관리자)
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 30
      responses:
        "200":
          description: 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponsePage"
        "401":
          description: "NOT_ADMIN"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        statusCode:
          type: integer
        error:
          type: string
        message:
          type: string
    OrderResponse:
      type: object
      properties:
        orderId:
          type: integer
        totalPrice:
          type: number
        createAt:
          type: string
          format: date-time
        memberId:
          type: integer
        orderDetailDtoList:
          type: array
          items:
            $ref: "#/components/schemas/OrderDetailDto"
    OrderDetailDto:
      type: object
      properties:
        id:
          type: integer
        productName:
          type: string
        price:
          type: number
        amount:
          type: integer
    OrderResponsePage:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/OrderResponse"
        pageable:
          type: object
        last:
          type: boolean
        totalPages:
          type: integer
        totalElements:
          type: integer
        size:
          type: integer
        number:
          type: integer
        sort:
          type: object
        first:
          type: boolean
        numberOfElements:
          type: integer
        empty:
          type: boolean
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
