openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
paths:
  /api/admin/products:
    post:
      summary: 상품 추가 (관리자)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ProductRequest"
      responses:
        "201":
          description: 생성됨
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductDetailDTO"
        "400":
          description: "DUPLICATE_PRODUCTNAME, IMAGE_FILE_EMPTY, IMAGE_FILE_SAVE_FAIL"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: "NOT_ADMIN"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/public/products/{productId}:
    get:
      summary: 상품 상세 정보 조회
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductDetailDTO"
        "404":
          description: "NOT_FOUND_PRODUCT"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/public/products/search:
    get:
      summary: 상품 검색
      parameters:
        - name: keyword
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 30
      responses:
        "200":
          description: 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductDTOPage"
        "400":
          description: "BAD_REQUEST"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/admin/products/{productId}:
    put:
      summary: 상품 수정 (관리자)
      security:
        - bearerAuth: []
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ProductRequest"
      responses:
        "200":
          description: 성공
        "400":
          description: "DUPLICATE_PRODUCTNAME, IMAGE_FILE_EMPTY, IMAGE_FILE_SAVE_FAIL"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: "NOT_ADMIN"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: "NOT_FOUND_PRODUCT"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      summary: 상품 삭제 (관리자)
      security:
        - bearerAuth: []
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: 성공
        "401":
          description: "NOT_ADMIN"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: "NOT_FOUND_PRODUCT"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        statusCode:
          type: integer
        error:
          type: string
        message:
          type: string
    ProductRequest:
      type: object
      properties:
        productName:
          type: string
        price:
          type: number
        description:
          type: string
        imageFiles:
          type: array
          items:
            type: string
            format: binary
    ProductDetailDTO:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
        description:
          type: string
        images:
          type: array
          items:
            type: string
    ProductDTO:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
        thumbnail:
          type: string
    ProductDTOPage:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/ProductDTO"
        pageable:
          type: object
        last:
          type: boolean
        totalPages:
          type: integer
        totalElements:
          type: integer
        size:
          type: integer
        number:
          type: integer
        sort:
          type: object
        first:
          type: boolean
        numberOfElements:
          type: integer
        empty:
          type: boolean
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
